---
deployment:
  tasks:
    # Set correct paths
    - export DEPLOYPATH=0143-D0EB/home/gyckh2yxxvf4/public_html
    - export BACKUPPATH=/home/gyckh2yxxvf4/site_backups
    - export LOGPATH=/home/gyckh2yxxvf4/deployment_logs
    
    # Create log directory if it doesn't exist
    - /bin/mkdir -p $LOGPATH
    - echo "=== Deployment started: $(date) ===" > $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - echo "Current directory: $(pwd)" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    
    # Fix parent directory permissions first - CRITICAL for access
    - echo "Setting parent directory permissions..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - chmod 755 /home/gyckh2yxxvf4 >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 755 /home >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 755 $DEPLOYPATH >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 755 $BACKUPPATH >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 755 $LOGPATH >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # Create backup directory if it doesn't exist
    - /bin/mkdir -p $BACKUPPATH
    
    # Backup current website before changes
    - echo "Creating backup..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - BACKUP_DIR=$BACKUPPATH/backup_$(date +%Y%m%d_%H%M%S)
    - /bin/mkdir -p $BACKUP_DIR
    - /bin/cp -R $DEPLOYPATH/* $BACKUP_DIR/ 2>> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log || true
    - /bin/cp -R $DEPLOYPATH/.htaccess $BACKUP_DIR/ 2>> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log || true
    - chmod -R 755 $BACKUP_DIR >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # CRITICAL: Show current directory and files to diagnose structure
    - echo "DEBUG: Current working directory is $(pwd)" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - echo "DEBUG: Listing files in current directory:" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - ls -la >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # Check that out directory was created correctly during Git clone
    - echo "Checking output directory..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - ls -la out >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || echo "Warning: 'out' directory not found!" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    
    # CRITICAL: Make sure .htaccess is included in deploy path
    - echo "Checking for .htaccess file in repository..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - if [ -f "out/.htaccess" ]; then 
        echo "Found .htaccess in out directory" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log;
      else 
        echo "WARNING: .htaccess not found in out directory!" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log;
      fi
    
    # Set permissions for output files BEFORE copying
    - echo "Setting output directory permissions..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - find out -type f -exec chmod 644 {} \; >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || true
    - find out -type d -exec chmod 755 {} \; >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || true
    
    # Temporarily lock deployment directory to prevent access during update
    - echo "<?php header('HTTP/1.1 503 Service Temporarily Unavailable'); header('Status: 503 Service Temporarily Unavailable'); header('Retry-After: 300'); ?><html><head><title>Maintenance in progress</title></head><body><h1>Maintenance in progress</h1><p>The website is currently being updated. Please try again in a few minutes.</p></body></html>" > $DEPLOYPATH/maintenance.php
    - echo "ErrorDocument 503 /maintenance.php" > $DEPLOYPATH/.htaccess.maintenance
    - /bin/cat $DEPLOYPATH/.htaccess >> $DEPLOYPATH/.htaccess.maintenance || true
    - /bin/mv $DEPLOYPATH/.htaccess.maintenance $DEPLOYPATH/.htaccess
    
    # CLEAN TARGET DIRECTORY - First, make sure we don't delete important server files
    - echo "Cleaning target directory..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -not -name ".well-known" -not -name "cgi-bin" -not -name ".htaccess" -not -name "maintenance.php" -exec rm -rf {} \; >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # DIRECTLY COPY FILES FROM FLATTENED BUILD TO ROOT LEVEL
    - echo "Copying built files directly to website root..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - /bin/cp -R out/* $DEPLOYPATH/ >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - /bin/cp -R out/.htaccess $DEPLOYPATH/ >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || echo "WARNING: Could not copy .htaccess file!" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    
    # VERIFY critical files were copied
    - echo "Verifying critical files were copied..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - ls -la $DEPLOYPATH/index.html >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || echo "WARNING: index.html not found after copy!" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - ls -la $DEPLOYPATH/.htaccess >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || echo "WARNING: .htaccess not found after copy!" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    
    # Create standard index.php that points to index.html for backward compatibility
    - echo "Creating PHP index file..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - echo "<?php header('Location: index.html'); ?>" > $DEPLOYPATH/index.php
    
    # ADDITIONAL FALLBACK: Create a basic index.html if it's still missing after copy
    - echo "Creating fallback index.html if needed..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - if [ ! -f "$DEPLOYPATH/index.html" ]; then 
        echo "CRITICAL: index.html still missing after copy! Creating emergency version..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log;
        echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Studio Clay</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:20px;text-align:center}</style></head><body><h1>Studio Clay</h1><p>Welcome to Studio Clay. The website is being updated. Please check back shortly.</p><p><a href="test.html">View Test Page</a></p></body></html>' > $DEPLOYPATH/index.html;
      fi
    
    # ADDITIONAL FALLBACK: Create a basic .htaccess if it's still missing
    - echo "Creating fallback .htaccess if needed..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - if [ ! -f "$DEPLOYPATH/.htaccess" ] || [ ! -s "$DEPLOYPATH/.htaccess" ]; then
        echo "CRITICAL: .htaccess missing or empty after copy! Creating emergency version..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log;
        echo 'DirectoryIndex index.html index.php' > $DEPLOYPATH/.htaccess;
        echo 'RewriteEngine On' >> $DEPLOYPATH/.htaccess;
        echo 'RewriteBase /' >> $DEPLOYPATH/.htaccess;
        echo 'RewriteCond %{REQUEST_FILENAME} !-f' >> $DEPLOYPATH/.htaccess;
        echo 'RewriteCond %{REQUEST_FILENAME} !-d' >> $DEPLOYPATH/.htaccess;
        echo 'RewriteRule . /index.html [L]' >> $DEPLOYPATH/.htaccess;
      fi
    
    # Set correct file permissions - thorough permission setting
    - echo "Setting file permissions..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - find $DEPLOYPATH -type f -exec chmod 644 {} \; >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - find $DEPLOYPATH -type d -exec chmod 755 {} \; >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # Set specific permissions for critical files
    - echo "Setting permissions for critical files..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - chmod 644 $DEPLOYPATH/.htaccess >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 644 $DEPLOYPATH/index.html >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 644 $DEPLOYPATH/index.php >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - chmod 644 $DEPLOYPATH/test.html >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1 || true
    
    # Final verification of index files
    - echo "Final verification of index files:" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - ls -la $DEPLOYPATH/index.* >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - ls -la $DEPLOYPATH/.htaccess >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # Remove maintenance mode
    - echo "Removing maintenance mode..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - rm -f $DEPLOYPATH/maintenance.php >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # Final parent directory permissions check
    - echo "Final parent directory permissions check..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - ls -la /home/ >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    - ls -la /home/gyckh2yxxvf4/ >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log 2>&1
    
    # Verify result
    - echo "Listing files after deployment..." >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - /bin/ls -la $DEPLOYPATH >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    
    # Final message
    - echo "=== Deployment completed: $(date) ===" >> $LOGPATH/deploy_$(date +%Y%m%d_%H%M%S).log
    - echo "Deployment completed: $(date)" > $DEPLOYPATH/deploy_info.txt