---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gyckh2yxxvf4/public_html
    # Clean the destination directory first
    - /bin/rm -rf $DEPLOYPATH/*
    
    # Copy the static files from the 'out' directory - this is what's missing!
    - /bin/cp -R out/* $DEPLOYPATH/
    
    # Copy the .htaccess file to ensure proper URL handling
    - /bin/cp out/.htaccess $DEPLOYPATH/.htaccess