---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gyckh2yxxvf4/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp .env.production $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    - /bin/cp postcss.config.mjs $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp eslint.config.mjs $DEPLOYPATH
    - /bin/cp next-env.d.ts $DEPLOYPATH
    - echo '#!/bin/bash\ncd $DEPLOYPATH\nnode_modules/.bin/next start -p 8080' > $DEPLOYPATH/start.sh
    - chmod +x $DEPLOYPATH/start.sh
    - cd $DEPLOYPATH
    - npm install --production