<?php
// Emergency index.php file
// This will either redirect to index.html or display its own content

if (file_exists('index.html')) {
    // If index.html exists, redirect to it
    header('Location: index.html');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Studio Clay</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            text-align: center;
            line-height: 1.6;
            color: #333;
        }
        h1 {
            color: #24292e;
            margin-bottom: 30px;
        }
        .info {
            background-color: #f6f8fa;
            border: 1px solid #e1e4e8;
            border-radius: 6px;
            padding: 15px;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <h1>Studio Clay</h1>
    <div class="info">
        <p>Welcome to Studio Clay. Our website is currently being updated.</p>
        <p>Please check back shortly for our full website.</p>
        <?php if (file_exists('test.html')): ?>
        <p><a href="test.html">View Test Page</a></p>
        <?php endif; ?>
    </div>
    <p><small>Generated by emergency-index.php at <?= date('Y-m-d H:i:s') ?></small></p>
</body>
</html> 